# Generated by Django 5.0 on 2025-12-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproductrelation',
            old_name='in_stock',
            new_name='quantity',
        ),
    ]
