# Generated by Django 5.0 on 2025-11-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'default_related_name': 'cart_items', 'ordering': ('-created_at',)},
        ),
    ]
