# Generated by Django 5.0 on 2025-11-28 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_author_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'default_related_name': 'order_items', 'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordered quantity'),
        ),
    ]
